export interface IntfMember{
    id: number,
    mem_id: number,
    company_id: number,
    rep_account: string,
    wp_mem_id: number,
    mem_level: number,
    adLocation: number,
    business_type: string,
    firstname: string,
    lastname: string,
    company_name: string,
    email: string,
    suite: string,
    address1: string,
    address2: string,
    city: string,
    state_code: string,
    state: string,
    country: string,
    country_code: string,
    postal: string,
    phone: string,
    phoneext: string,
    mobile: string,
    cellphone: string,
    fax: string,
    website: string,
    advdaystxt: string,
    advtimetxt: string,
    advcontacttype: string,
    newsletteryn: string,
    profile_image: string,
    profile_logo: string,
    profile_description: string,
    company_description: string,
    rep_term: string,
    rep_start_date: string,
    rep_end_date: string,
    rep_autopay: number,
    is_active: number,
    is_primary: number,
    added_date:string,
    modified_date:string
     //reg_ip:string
}